# -*- coding: utf-8 -*-
"""SubfieldsInAI.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17sRQBXRkgPfwGeTNeugQIsqZzjIfqI8F
"""

class SubfieldsInAI:
  def Subfields():
      list = [
      "Machine Learning",
      "Neural Networks",
      "Vision",
      "Robotics",
      "Speech Processing",
      "Natural Language Processing"
      ]
      print("Sub-fields in AI are:")
      for field in list:
          print(field)

SubfieldsInAI.Subfields()